### ISSUE TITLE
Adding support to Java and C#

### ISSUE THREAD

**Issue by leandrodamascena** [nideveloper/CDK-SPA-Deploy#178]
Hi dude, good night. 

Since many stacks (I see at least 3) in CDKPatterns uses this project as Construct to deploy static websites in S3, what do you think of adding support to C# and Java in jsii targets? Or even refactor this project using Projen? 

Let me know what you think about and how I can help you.

Thank you for your attention.

**Comment by SnapPetal** [comment]
I do not want to take away from this project.  I did start a new project using projen and using web distributions instead. I would love the help to port to Java and C#.

https://github.com/SnapPetal/cdk-cloudfront-deploy

**Comment by nideveloper** [comment]
This project doesn't need any code changes to support dotnet and Java. I have been taking a break over the holiday period but here is the dotnet version published https://www.nuget.org/packages/CDKSPADeploy/1.80.0 , I will publish Java after sonatype approve the namespace

**Comment by nideveloper** [comment]
Apparently the approval can take up to 2 business days so that could be next week depending on if they work new years day

**Comment by leandrodamascena** [comment]
Ohh, very good that you added the NuGet and Sonartype package manager. I created a new namespace two weeks ago and the process was very fast, about 12 hours.

Thanks for feedback, Matt.

**Comment by nideveloper** [comment]
I actually wasn't sure if anyone would want to deploy a website from Java/.Net CDK when I created this I couldn't picture myself deploying a react site with a Java Infra backend at the time but your livestream pattern and a few other things I have seen since have changed my mind on that so when go becomes stable I will add it too. Why not support everything?

**Comment by leandrodamascena** [comment]
Yes, and as you didn't need to change anything. I think you added jsii targets or gh actions to "deploy" to these package managers.

And in doing so you follow the jsii/cdk philosophy: the user doesn't care about the language, we support everyone (of course the most populars one haha).

btw, I have a CDK stack in production that creates buckets and deploys a single website (made using https://gohugo.io/) for S3 every time someone needs it. And this stack was built using C#,  so I'm going to migrate it to SPADeploy :)

**Comment by nideveloper** [comment]
Java should be there now though it says sync to maven central can take 10 mins for publish and 2 hours for search. 

Converted to Github actions as well:
https://github.com/nideveloper/CDK-SPA-Deploy/blob/master/.github/workflows/main.yml
