### ISSUE TITLE
jsii errors -- 

### ISSUE THREAD

**Issue by ksteward** [nideveloper/CDK-SPA-Deploy#191]
using the simple Python version:
  `SPADeploy( self, 'spaDeployo' ).create_site_with_cloudfront( ...)`
I get the following stack trace:

> jsii.errors.JavaScriptError: 
>   Error: ENOENT: no such file or directory, open '/tmp/jsii-kernel-NX9cjp/node_modules/@aws-cdk/lambda-layer-awscli/layer/Dockerfile'
>       at Object.openSync (fs.js:476:3)
>       at Object.readFileSync (fs.js:377:35)
>       at hashFile (/tmp/jsii-kernel-NX9cjp/node_modules/@aws-cdk/lambda-layer-awscli/lib/awscli-layer.js:31:20)
>       at new AwsCliLayer (/tmp/jsii-kernel-NX9cjp/node_modules/@aws-cdk/lambda-layer-awscli/lib/awscli-layer.js:21:28)
>       at new BucketDeployment (/tmp/jsii-kernel-NX9cjp/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.js:25:22)
>       at SPADeploy.createSiteWithCloudfront (/tmp/jsii-kernel-NX9cjp/node_modules/cdk-spa-deploy/lib/spa-deploy/spa-deploy-construct.js:134:9)
>       at /home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3380:51
>       at Kernel._wrapSandboxCode (/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4040:16)
>       at /home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3380:25
>       at Kernel._ensureSync (/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4017:20)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "app.py", line 9, in <module>
>     PrivacyCdk1Stack(app, "privacy-cdk1")
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_runtime.py", line 69, in __call__
>     inst = super().__call__(*args, **kwargs)
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/privacy_cdk1/privacy_cdk1_stack.py", line 18, in __init__
>     website_folder='../website/dist/website'
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/spa_deploy/__init__.py", line 424, in create_site_with_cloudfront
>     return jsii.invoke(self, "createSiteWithCloudfront", [config])
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 125, in wrapped
>     return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 319, in invoke
>     args=_make_reference_for_native(self, args),
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
>     return self._process.send(request, InvokeResponse)
>   File "/home/ksteward/projects/cdk1/privacy-cdk1/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 332, in send
>     raise JSIIError(resp.error) from JavaScriptError(resp.stack)
> jsii.errors.JSIIError: ENOENT: no such file or directory, open '/tmp/jsii-kernel-NX9cjp/node_modules/@aws-cdk/lambda-layer-awscli/layer/Dockerfile'
> Subprocess exited with error 1

I'm using CDK 1.81.0.  

Does the CDK-SPA-Deploy require an older CDK?  Or is something else amiss?

**Comment by ksteward** [comment]
resolved now.  Turned out some dependencies were not installed yet.

**Comment by cdk-patterns** [comment]
If this breaks again for you it looks like CDK has a problem with website deploys in 1.81.0 - https://github.com/aws/aws-cdk/issues/12291 they should release a new version soon which would include the patch
