### ISSUE TITLE
React Apps with a configured React Router need to have the errorDoc configured.

### ISSUE THREAD

**Issue by bigheadoreilly** [nideveloper/CDK-SPA-Deploy#4]
https://stackoverflow.com/questions/51218979/react-router-doesnt-work-in-aws-s3-bucket 

Should simply be a matter of configuring the Error Document for the S3 web bucket.

I will submit a fix for review shortly that allows the developer to set the error document with the main SPADeploy constructor.

**Comment by nideveloper** [comment]
version 0.8.0 released with fix
