### ISSUE TITLE
Please dont use screenshots for code 

### ISSUE THREAD

**Issue by uwinkler** [nideveloper/CDK-SPA-Deploy#90]
Love your work 👍  

And it would be really nice if you could use code snippets in your documentation, instead of screenshots. You know - to copy and past ;)

**Comment by nideveloper** [comment]
I agree it was originally snippets but JSII broke in the doc generation for Python so this was a quick workaround 8 months ago that has just stuck. When I made this project I didn't expect 10,000 downloads from NPM so 100% agree with you it's time to refactor

**Comment by FavorWedge** [comment]
I will do a quick PR later to update the images later tonight.

**Comment by SnapPetal** [comment]
#110
